# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskanswer',
            name='user',
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
