# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_auto_20170921_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5)),
                ('sex', models.CharField(max_length=1)),
                ('political', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=30)),
                ('classes', models.CharField(max_length=4)),
                ('qq', models.CharField(max_length=15)),
                ('tel', models.CharField(max_length=20)),
                ('swap', models.CharField(max_length=1)),
                ('first', models.CharField(max_length=8)),
                ('second', models.CharField(blank=True, max_length=8, null=True)),
                ('award', models.TextField(blank=True, max_length=500, null=True)),
                ('tink', models.TextField(blank=True, max_length=500, null=True)),
                ('advice', models.TextField(blank=True, max_length=500, null=True)),
                ('attach', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskAnswer',
        ),
    ]
