# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0005_auto_20170923_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=500, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_Admit', to='Task.ApplyForm')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_Mark', to='Task.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5)),
                ('pwd', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Mark', to='eva.User'),
        ),
    ]
